### ISSUE TITLE
Some questions about P+

### ISSUE THREAD

**Issue by SMU-Terry** [wagiminator/ATmega-Soldering-Station#20]
![image](https://user-images.githubusercontent.com/64240681/141100779-33c1461a-1774-413c-bbbb-d58c7c841820.png)
the P+ net actually directly connects with GND, is that correct? hope to get a reasonable answer, thanks

**Comment by wagiminator** [comment]
No, it doesn't. Connections are marked with a junction dot: https://www.autodesk.com/products/eagle/blog/top-10-tips-draw-next-schematic-design-like-pro/

**Comment by SMU-Terry** [comment]
thank you so much, I've got it, and I see that compare to the low version, you add D4 as a voltage regulator in Version 2.7, may I ask where is this idea comes from?

**Comment by wagiminator** [comment]
I added that to protect the MOSFET. The Zener diode D4 limits the voltage between the gate and source of the MOSFET to about 18V. Since the maximum gate-source voltage of the MOSFET is 20V, but this is exceeded at higher supply voltages of the soldering station, this could lead to damage to the MOSFET in the long term without the diode.

**Comment by SMU-Terry** [comment]
thank you so much!
