### ISSUE TITLE
5V Voltage regulator

### ISSUE THREAD

**Issue by dahayer** [wagiminator/ATmega-Soldering-Station#25]
Can i use a buck converter (step down)  instead of 78m05 for better efficiency and less heat ? thanks

**Comment by wagiminator** [comment]
Hi, due to the quite low current consumption of the circuit, the efficiency and heat generation are negligible. However, a linear regulator generates significantly less noise than a switching regulator, which allows for a cleaner temperature measurement. If you still want it, V1 of the soldering station was implemented with a buck converter.

**Comment by dahayer** [comment]
Thank you for your response.
